Repository canonical/chisel, pull requests merged in 2023-09, with the labels that each got.

#66 fix: use proper HTTP clients to fetch files
  internal/archive/archive.go
Labels: Simple

#82 slicer/test: Set archive options from release
  internal/slicer/slicer_test.go
Labels: Simple, Priority

#97 Switch from kinetic to focal in spread tests
  tests/basic/task.yaml
  tests/use-a-custom-chisel-release/task.yaml
Labels: Priority
