Repository canonical/chisel, pull requests merged in 2024-06, with the labels that each got.

#134 feat: support for several slices of the same package
  internal/deb/extract.go
  internal/deb/extract_test.go
  internal/setup/setup_test.go
  internal/slicer/slicer.go
  internal/slicer/slicer_test.go
  internal/testutil/permutation.go
  internal/testutil/permutation_test.go
Labels: Priority

#136 refactor: split slicer into steps and remove unnecessary state
  go.mod
  internal/deb/extract_test.go
  internal/setup/setup.go
  internal/slicer/slicer.go
  snap/snapcraft.yaml
  spread.yaml
Labels: Simple, Priority

#99 feat: add find command
  cmd/chisel/cmd_cut.go
  cmd/chisel/cmd_find.go
  cmd/chisel/cmd_find_test.go
  cmd/chisel/cmd_help.go
  cmd/chisel/export_test.go
  cmd/chisel/helpers.go
  internal/strdist/strdist.go
  tests/find/task.yaml
Labels: Simple
