Repository canonical/chisel, pull requests merged in 2024-10, with the labels that each got.

#162 refactor: tune error message for invalid generate value
  internal/setup/setup.go
  internal/setup/setup_test.go
Labels: Simple

#163 fix: info supports "generate" paths
  internal/setup/setup.go
  internal/setup/setup_test.go
Labels: Simple, Priority, Bug

#150 fix: deprecate "chisel-v1" format
  cmd/chisel/cmd_info_test.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  internal/slicer/slicer_test.go
Labels: Simple, Priority

#159 feat: validate manifest before writing
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/slicer/slicer_test.go
Labels: Priority

#152 ci: report vulnerabilities and fail on HIGH,CRITICAL
  .github/workflows/security.yaml
Labels: Simple

#160 feat: support multiple archives with "priority" field
  cmd/chisel/cmd_find_test.go
  cmd/chisel/cmd_info_test.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  internal/slicer/slicer.go
  internal/slicer/slicer_test.go
  internal/testutil/archive.go
Labels: Priority
