Repository canonical/chisel, pull requests merged in 2025-01, with the labels that each got.

#189 chore: update golang.org/x/crypto
  go.mod
  go.sum
Labels: Simple

#188 chore: add security policy
  SECURITY.md
Labels: Simple

#190 chore(snap): rename system-files interface
  snap/snapcraft.yaml
Labels: Simple

#179 feat: add support for hard links
  internal/archive/archive.go
  internal/cache/cache.go
  internal/deb/extract.go
  internal/deb/extract_test.go
  internal/fsutil/create.go
  internal/fsutil/create_test.go
  internal/manifest/manifest.go
  internal/manifest/manifest_test.go
  internal/manifest/report.go
  internal/manifest/report_test.go
  internal/setup/setup.go
  internal/slicer/slicer.go
  internal/slicer/slicer_test.go
  internal/testutil/archive.go
  internal/testutil/nopcloser.go
  internal/testutil/pkgdata.go
  internal/testutil/treedump.go
Labels: Priority

#193 chore(ci): bump artifact actions to v4
  .github/workflows/build.yml
  .github/workflows/snap.yml
  .github/workflows/tests.yaml
Labels: Simple

#192 chore(snap): add security advisory and contact email
  snap/snapcraft.yaml
Labels: Simple

#182 chore: expose manifest reading and jsonwall as packages
  .github/scripts/external-packages-license-check.go
  .github/workflows/license.yaml
  internal/apachetestutil/manifest.go
  internal/apacheutil/log.go
  internal/apacheutil/suite_test.go
  internal/apacheutil/util.go
  internal/apacheutil/util_test.go
  internal/manifestutil/log.go
  internal/manifestutil/manifestutil.go
  internal/manifestutil/manifestutil_test.go
  internal/manifestutil/report.go
  internal/manifestutil/report_test.go
  internal/manifestutil/suite_test.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  internal/setup/yaml.go
  internal/slicer/slicer.go
  internal/slicer/slicer_test.go
  public/jsonwall/jsonwall.go
  public/jsonwall/jsonwall_test.go
  public/jsonwall/log.go
  public/jsonwall/suite_test.go
  public/manifest/log.go
  public/manifest/manifest.go
  public/manifest/manifest_test.go
  public/manifest/suite_test.go
Labels: Priority, Polish
